grpc:
  port: 50051
management:
  server:
    port: 9001
  endpoints:
      web:
        exposure:
          include: ["info", "health", "prometheus"]
        base-path: /
        path-mapping:
          prometheus: /metrics
influx-db:
  data-source:
    url: $(INFLUX_DB_HOST)
    username: $(INFLUX_DB_USERNAME)
    password: $(INFLUX_DB_PASSWORD)
    database: $(INFLUX_DB_DATABASE)
name: views-api
version: 1.0.0
logging:
  level:
    root: INFO